# Generated by Django 3.2.16 on 2022-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default='2000-12-12'),
            preserve_default=False,
        ),
    ]
